git:
  depth: 1

matrix:
  include:
  - language: node_js
    node_js:
      - "10"
      - "12"
    os: 
      - linux
    env:
      - APP_BASE=packages/dispatcher-converter
  - language: node_js
    node_js:
      - "10"
      - "12"
    os: 
      - linux
    env:
      - APP_BASE=packages/index-converter
  - language: node_js
    node_js:
      - "10"
      - "12"
    os: 
      - linux
    env:
      - APP_BASE=packages/repository-modernizer

before_install: cd $APP_BASE

install:
  - npm version
  - npm install
  - npm install codecov

script:
  - npm test
  - npm run coverage
 

# safelist (prevent double builds in PRs)
branches:
  only:
  - master
  - /^greenkeeper/.*$/