git:
  depth: 1

matrix:
  include:
  - language: node_js
    node_js:
      - "10"
      - "12"
    os: 
      - linux
    target: auto
    threshold: 0%
    base: auto 
    flags: 
      - unit
    paths: 
      - packages
    branches: 
      - master
    if_ci_failed: error
    only_pulls: false
    env:
      - APP_BASE=packages/dispatcher-converter

  - language: node_js
    node_js:
      - "10"
      - "12"
    os: 
      - linux
    target: auto
    threshold: 0%
    base: auto 
    flags: 
      - unit
    paths: 
      - packages
    branches: 
      - master
    if_ci_failed: error
    only_pulls: false
    env:
      - APP_BASE=packages/index-converter

  - language: node_js
    node_js:
      - "10"
      - "12"
    os: 
      - linux
    target: auto
    threshold: 0%
    base: auto 
    flags: 
      - unit
    paths: 
      - packages
    branches: 
      - master
    if_ci_failed: error
    only_pulls: false
    env:
      - APP_BASE=packages/repository-modernizer

before_install: cd $APP_BASE

install:
  - npm version
  - npm install

script:
  - npm test
  - bash <(curl -s https://codecov.io/bash)
 

# safelist (prevent double builds in PRs)
branches:
  only:
  - master
  - /^greenkeeper/.*$/