language: node_js
sudo: false
git:
  depth: 10

os:
  - windows
  - linux

node_js:
  - "10"
  - "12"

matrix:
  include:
  - language: node_js
    env:
      - APP_BASE=packages/dispatcher-converter
  - language: node_js
    env:
      - APP_BASE=packages/index-converter
  - language: node_js
    env:
      - APP_BASE=packages/repository-modernizer

before_install: cd $APP_BASE

install:
  - npm version
  - npm install
script:
  - npm test
  - npm run coverage

after_success:
- bash <(curl -s https://codecov.io/bash)

# safelist (prevent double builds in PRs)
branches:
  only:
  - master
  - /^greenkeeper/.*$/