name: Publish Packages

on:
  push:
    branches:
      - master  # Change this to your default branch

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile --non-interactive        

      - name: Execute Tests
        run: yarn test

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@b3300fad33b6ab794313da28d27424c0e2f78991
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      # Leave this as is, it's automatically generated
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}  # This will be shared with your repo as an org secret
